"""Stage 1 — tagged rewritten markdown -> structured IR.

The input is no longer the raw PDF-converted markdown. `rewrite_medical_md.py`
now owns that job: it rewrites the slide dump into a fresh, tagged study
document, and *that* is what this stage parses. Everything Stage 1 used to do
by inference — telling figure prose from material content, flattening bullets,
distributing headings, guarding a rewrite — is done structurally upstream by
the tags. So this stage does no rewriting, makes no LLM calls, and reaches no
judgement about what any passage means. It maps tags onto chunk kinds:

    <con>       -> prose           <cap>       -> caption
    <def>       -> definition      <tbl><cap>  -> table_caption
    <key>       -> keypoint        <tbl><con>  -> table
    <clin>      -> clinical        <ref>       -> reference
    <sum>       -> summary         <obj>       -> objective
    <desc>      -> figure_content

Only assertable text becomes a `Chunk`. A `<desc>` and a `<tbl>`'s `<con>` are
assertable: the rewriter restates a diagram and a grid as standalone sentences
on the same one-claim-per-sentence contract as body prose. A `<cap>` is not, so
captions are stored on the `Figure` or `Table` instead, and objectives and
bibliography become `Passage`s: retained, with offsets, but never assertable.
All of it is still written to the normalized file, so every piece of the
document has a position even when it is not a chunk.

Inline markup (`<figref>`, `<tblref>`, `<sup>`, `<sub>`) is unwrapped by
`normalize_inline` before the block parse, because it belongs inside a sentence
rather than between elements. Cross-references survive the unwrap as
`[[FIG:id]]` / `[[TBL:id]]` anchors, which `lift_anchors` then moves onto the
citing chunk so the prose keeps exact offsets.

LaTeX gets one of two treatments. A sentence of body text carrying a math span
never becomes chunk text, because a formula reaches the extractor as a single
opaque token; `drop_formula_sentences` removes it from prose, from a restated
grid and from a `<desc>`, and `config.DROP_FORMULA_SENTENCES` turns that off. A
heading, a caption, an objective and the bibliography keep their sentence and
lose only the markup, through `flatten_math`: dropping a heading would cost its
section the `section_path` and the id built from it. Nothing carrying LaTeX
markup reaches the normalized file either way.

Two things this stage still owns, because nothing else can:

  * **Offsets.** It writes a tag-free rendering to `Document.normalized_path`
    and every chunk indexes into that file exactly, so Stage 2's substring
    grounding guards keep working and any triple can be traced back to text.
  * **Provenance.** The document it parses was written by a model. `<src>`
    records what the rewriter was given and which model wrote it, and those go
    into `Source.origin` / `.generator` so Stage 6 can assert the original as
    `dcterms:source` and the rewrite as `prov:wasGeneratedBy`. Without that the
    graph would report model-authored prose as what the textbook said.

The parser is deliberately tolerant: the tagged format has drifted across
rewriter versions (list items appear either as `<pt>`/`<term>`/`<goal>`
elements or as bare `- ` bullets; headings sometimes keep their `#` markers;
failed sections appear either as `<note status="failed">` or as a parenthetical
inside `<con>`), and a corpus generated by an older build must still parse.

Stdlib only. No network, no models, nothing to configure.
"""
from __future__ import annotations

import itertools
import os
import re
import time
from dataclasses import dataclass, field
from typing import Optional

from .ir import Document, Source, Chunk, Figure, Passage, Table
from . import config
from . import console

# ---------------------------------------------------------------------------
# Tolerant tag scanner
# ---------------------------------------------------------------------------

KNOWN_TAGS = ("doc", "meta", "title", "topic", "src", "obj", "goal", "sec",
              "head", "con", "fig", "cap", "desc", "key", "pt", "def", "term",
              "clin", "tbl", "note", "sum", "ref", "cit")

_TAG_RE = re.compile(r"<(/?)(" + "|".join(KNOWN_TAGS) + r")(\s[^>]*)?>", re.I)
_ATTR_RE = re.compile(r'(\w+)\s*=\s*"([^"]*)"')

# `[FIGURE:p2_b3]` — the marker carried through from the original document.
FIGURE_MARKER_RE = re.compile(r"\[\s*FIGURE\s*:\s*([^\]\n]+?)\s*\]", re.I)
# `[[FIG:p2_b3]]` / `[[TBL:tbl-2-1]]`, the internal anchor form. Older rewriters
# wrote `[[FIG:id]]` into the prose directly; the current one wraps the mention
# in `<figref>`/`<tblref>` and `normalize_inline` rewrites it to this. The
# surrounding horizontal space is captured too, so `lift_anchors` can tell
# `(Figure 2-1[[FIG:x]])` from a free-standing ` [[FIG:x]] `.
_ANCHOR_RE = re.compile(
    r"(?P<lead>[ \t]*)\[\[\s*(?P<kind>FIG|TBL)\s*:\s*(?P<id>[^\]\n]+?)\s*\]\]"
    r"(?P<trail>[ \t]*)")

# Inline markup that lives *inside* element content, not between elements.
# It cannot go through `parse_tagged`: that builds a block tree, and a child
# node's text is emitted after its parent's, joined by a newline. Running
# `<sup>` or `<figref>` through it would lift the fragment out of the sentence
# it belongs to and put it on a line of its own. So these are unwrapped in the
# raw text first, before the block parse ever sees them.
_SUPSUB_RE = re.compile(r"</?su[bp]>", re.I)
_XREF_RE = re.compile(r'<(fig|tbl)ref\b[^>]*\bid="([^"]*)"[^>]*>(.*?)</\1ref>',
                      re.I | re.S)

# A LaTeX span, which the rewriter leaves inline: `$2.0 \times 10^{-2}$`,
# `$[OH^{-}]$`, `${ \mathsf { C O } } _ { 2 }$`. Both delimiters are a single
# `$` and never straddle a line break.
_MATH_RE = re.compile(r"\$([^$\n]+)\$")
# Font and grouping commands, which mean nothing once the markup is gone.
_MATH_FONT_RE = re.compile(
    r"\\(?:math(?:sf|rm|bf|it|frak|cal|tt)|text(?:sf|rm|bf|it)?"
    r"|operatorname|left|right)\s*")
# Commands standing for a character the normalized text can hold directly.
_MATH_SYMBOLS = {r"\times": "\u00d7", r"\cdot": "\u00b7", r"\pm": "\u00b1",
                 r"\approx": "\u2248", r"\leq": "\u2264", r"\geq": "\u2265",
                 r"\rightarrow": "\u2192", r"\to": "\u2192",
                 r"\Delta": "\u0394", r"\delta": "\u03b4", r"\phi": "\u03c6",
                 r"\alpha": "\u03b1", r"\beta": "\u03b2", r"\gamma": "\u03b3"}
_MATH_SYMBOL_RE = re.compile(
    "(?:" + "|".join(re.escape(name) for name in
                     sorted(_MATH_SYMBOLS, key=len, reverse=True))
    + r")(?![A-Za-z])")
# Whatever command is left is unknown or an OCR artifact — the corpus contains
# `\ight` where `\right` was scanned. Dropping the command keeps its operands.
_MATH_COMMAND_RE = re.compile(r"\\[A-Za-z]+\s*|\\(.)")
# Grouping braces and the script markers. Scripts are flattened by
# concatenation, the same convention `normalize_inline` applies to `<sup>` and
# `<sub>`, so `10^{-7}` reads `10-7` and `K_w` reads `Kw`.
_MATH_MARKUP_RE = re.compile(r"[{}_^]")
# A sentence boundary: a terminator, then whitespace, then something that can
# open a sentence. The lookahead excludes a digit so `5. 0` cannot split, and a
# decimal point is never followed by whitespace, so `2.0 mol/L` stays whole.
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+(?=[^\s\d])")

_MD_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+", re.M)
_BULLET_RE = re.compile(r"^\s*(?:[-+\u2022\u2023\u25aa\u25e6]|\*(?!\*)|\d+[.)])\s+")
_EMPHASIS_RE = re.compile(r"(\*{1,3}|_{2,3})(?=\S)(.+?)(?<=\S)\1", re.S)

_FAILED_RE = re.compile(r"could not be generated", re.I)


@dataclass
class Node:
    tag: str
    attrs: dict = field(default_factory=dict)
    children: list = field(default_factory=list)
    text: str = ""

    def find(self, tag: str) -> Optional["Node"]:
        for c in self.children:
            if c.tag == tag:
                return c
        return None

    def findall(self, tag: str) -> list:
        return [c for c in self.children if c.tag == tag]

    def flat_text(self) -> str:
        parts = [self.text]
        for c in self.children:
            parts.append(c.flat_text())
        return "\n".join(p for p in parts if p.strip()).strip()


def normalize_inline(text: str) -> str:
    """Unwrap inline markup so it survives inside the sentence it belongs to.

    `<sup>`/`<sub>` are dropped and their content joined with *no* separator.
    The corpus writes `[H<sup>+</sup>]`, `sp<sup>3</sup>`, `pK<sub>a</sub>` and
    `M<sub>r</sub>`: a space would split a formula into two tokens, and dropping
    the content would turn H+ into H, a different species. Superscript exponents
    such as `10<sup>-9</sup>` flatten to `10-9`, which is lossy, but writing
    `10^-9` would put characters into the text that the source never had.

    `<figref>`/`<tblref>` keep their mention text and gain a trailing
    `[[FIG:id]]` / `[[TBL:id]]` anchor, which `lift_anchors` strips back off
    once the text is inside its chunk. Routing through the anchor rather than
    reading the attribute here is what keeps the id attached to the *chunk* that
    cited it, which is the only reason the reference is worth having.

    Returns the rewritten text; the input string is untouched.
    """
    text = _XREF_RE.sub(
        lambda m: f"{m.group(3)}[[{m.group(1).upper()}:{m.group(2)}]]", text)
    return _SUPSUB_RE.sub("", text)


def parse_tagged(text: str) -> Node:
    """Tagged document -> a shallow node tree.

    Hand-rolled rather than XML: the body carries markdown, bare ampersands and
    `[[FIG:...]]` anchors, so a strict parser would reject documents that are
    perfectly usable. Unknown tags fall through as text; an unclosed tag is
    closed implicitly when its parent closes.
    """
    root = Node("doc")
    stack = [root]
    pos = 0
    for m in _TAG_RE.finditer(text):
        chunk = text[pos:m.start()]
        if chunk.strip():
            stack[-1].text = (stack[-1].text + "\n" + chunk).strip()
        pos = m.end()
        closing, tag = bool(m.group(1)), m.group(2).lower()
        if closing:
            for i in range(len(stack) - 1, 0, -1):
                if stack[i].tag == tag:
                    del stack[i:]
                    break
        else:
            attrs = dict(_ATTR_RE.findall(m.group(3) or ""))
            node = Node(tag, attrs)
            if tag == "doc" and len(stack) == 1:
                root.attrs.update(attrs)
                continue
            stack[-1].children.append(node)
            stack.append(node)
    tail = text[pos:]
    if tail.strip():
        stack[-1].text = (stack[-1].text + "\n" + tail).strip()
    return root


# ---------------------------------------------------------------------------
# Text cleanup (repair only — never rewriting)
# ---------------------------------------------------------------------------

def strip_emphasis(text: str) -> str:
    prev = None
    while prev != text:
        prev = text
        text = _EMPHASIS_RE.sub(lambda m: m.group(2), text)
    return text


MARKER_SCANS = (
    ("heading marker", re.compile(r"^\s{0,3}#{1,6}\s+", re.M)),
    ("bold/italic marker", re.compile(r"\*")),
    ("bullet marker", re.compile(r"^\s*(?:[-+\u2022]|\d+[.)])\s+", re.M)),
)


def scan_markers(raw: str) -> list[dict]:
    """Report markdown markers left in the tagged document.

    The current rewriter emits none of these — the tags carry the structure, so
    a `##` or a `**` means it regressed. `clean_text` still repairs them, but
    repairing silently would hide the regression, so each kind is reported once
    with an example. Applies to tag *content* only; `[FIGURE:id]` markers and
    `[[FIG:id]]` anchors are not markdown and are left alone.
    """
    body = _TAG_RE.sub("", raw)
    body = FIGURE_MARKER_RE.sub("", _ANCHOR_RE.sub("", body))
    out = []
    for label, pattern in MARKER_SCANS:
        hits = pattern.findall(body)
        if hits:
            line = next((ln.strip() for ln in body.splitlines() if pattern.search(ln)), "")
            out.append({"stage": "stage1-marker", "reason": f"{label} in tagged content",
                        "count": len(hits), "example": line[:120]})
    return out


def clean_text(text: str) -> str:
    """Remove markdown scaffolding, if any survived.

    Repair, not rewriting — the words are untouched. The current rewriter leaves
    none of this behind; `scan_markers` reports whatever turns up so a silent
    repair cannot mask a rewriter regression.
    """
    out = []
    for line in text.splitlines():
        line = _MD_HEADING_RE.sub("", line)
        line = _BULLET_RE.sub("", line, count=1)
        line = strip_emphasis(line)
        # Whatever asterisks survive emphasis-matching are orphans from the
        # older rewriter's bullet bug ("- *Follicular cells** — ..."), which
        # leaves one behind mid-line. They are markup, never content, and left
        # in they would sit inside Stage 2's span offsets and evidence strings.
        line = line.replace("*", "")
        line = re.sub(r"[ \t]{2,}", " ", line).strip()
        if line:
            out.append(line)
    return "\n".join(out).strip()


def _join_math_tokens(tokens: list[str]) -> str:
    """Rejoin the whitespace-separated pieces of a stripped math span.

    The corpus writes its LaTeX one character per token, `\\mathsf { p } K _ {
    \\mathsf { a } }`, so most of the whitespace is padding rather than a word
    break. A gap is kept only where at least one side is more than a single
    character, which reads `p K a` back as `pKa` while leaving `moles2 per
    liter2` and `Kw = [H+][OH-]` spaced as written.
    """
    out = []
    for index, token in enumerate(tokens):
        if index and (len(tokens[index - 1]) > 1 or len(token) > 1):
            out.append(" ")
        out.append(token)
    return "".join(out)


def flatten_math(text: str) -> str:
    """Rewrite every LaTeX span in `text` as the plain characters it denotes.

    Returns the text with each `$...$` replaced; text outside a span is
    untouched. `$\\mathsf { p } K _ { \\mathsf { a } }$` becomes `pKa` and
    `$2.0 \\times 10^{-2}$` becomes `2.0 × 10-2`.

    This is what headings, captions and objectives get instead of
    `drop_formula_sentences`: their math is nearly all notation for a named
    quantity, and dropping a heading would cost its section the `section_path`
    and the id built from it. Superscripts and subscripts flatten by
    concatenation, so an exponent loses its sign convention; that is the same
    trade `normalize_inline` already makes for `<sup>` and `<sub>`, and it keeps
    the source's own digits rather than inventing a notation for them.
    """
    def render(match: re.Match) -> str:
        body = _MATH_FONT_RE.sub("", match.group(1))
        body = _MATH_SYMBOL_RE.sub(lambda m: _MATH_SYMBOLS[m.group(0)], body)
        body = _MATH_COMMAND_RE.sub(lambda m: m.group(1) or "", body)
        return _join_math_tokens(_MATH_MARKUP_RE.sub("", body).split())

    return _MATH_RE.sub(render, text)


def drop_formula_sentences(text: str) -> str:
    """Remove every sentence carrying a LaTeX math span.

    Returns the text with the surviving sentences rejoined, line structure
    intact. A no-op when `config.DROP_FORMULA_SENTENCES` is off.

    The whole sentence goes, not just the span: a formula reaches Stage 2 as one
    opaque token, and a sentence stripped of the only quantity it was written to
    carry ("The concentration of hydroxide is .") asserts something the source
    never said. Lines are preserved because a restated grid is one row per line,
    and fusing a dropped row's neighbours would invent a claim spanning two
    rows.

    Headings, captions and objectives go through `flatten_math` instead, which
    keeps the sentence and rewrites the notation.
    """
    if not config.DROP_FORMULA_SENTENCES:
        return text
    kept_lines = []
    for line in text.splitlines():
        kept = " ".join(s for s in _SENTENCE_SPLIT_RE.split(line)
                        if not _MATH_RE.search(s))
        kept = re.sub(r"[ \t]{2,}", " ", kept).strip()
        if kept:
            kept_lines.append(kept)
    return "\n".join(kept_lines)


def split_items(node: Node) -> list[str]:
    """Items of a list container, whichever way the rewriter emitted them:
    as child elements (`<pt>`, `<term>`, `<goal>`, `<cit>`) or as `- ` bullets."""
    items = [clean_text(c.flat_text()) for c in node.children
             if c.tag in ("pt", "term", "goal", "cit")]
    items = [i for i in items if i]
    if items:
        return items
    return [ln for ln in (clean_text(node.text)).splitlines() if ln.strip()]


def lift_anchors(text: str) -> tuple[str, list[str], list[str]]:
    """Pull figure and table anchors out of prose.

    Returns `(text, fig_ids, tbl_ids)`. The anchors must not survive into chunk
    text: Stage 2 requires its `evidence` to be an exact substring of the chunk,
    and an anchor sitting mid-sentence corrupts every span offset after it. The
    association is kept on the chunk instead.

    An anchor is replaced by a single space only when it had space on *both*
    sides, which is how a free-standing `[[FIG:id]]` was written. The anchor
    `normalize_inline` appends sits flush against its mention, so
    `(Figure 2-1[[FIG:fig-2-1]]).` has to close back up to `(Figure 2-1).`
    rather than gain a space before the bracket.
    """
    fig_ids, tbl_ids = [], []
    for m in _ANCHOR_RE.finditer(text):
        (fig_ids if m.group("kind").upper() == "FIG" else tbl_ids).append(
            m.group("id").strip())
    cleaned = _ANCHOR_RE.sub(
        lambda m: " " if (m.group("lead") and m.group("trail")) else "", text)
    cleaned = re.sub(r"[ \t]{2,}", " ", cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip(), fig_ids, tbl_ids


def slug(text: str, max_len: int = 48) -> str:
    """A URI-safe, human-readable identifier: 'Thyroid Hormones' -> 'thyroid-hormones'.

    Used for section and group ids that end up inside a graph URI, so it is
    restricted to characters that survive N-Quads and a shell argument without
    quoting — a scope you cannot type is a scope you cannot extract.
    """
    out = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return out[:max_len].rstrip("-")


def parse_src(line: str) -> dict:
    """`source: x.md | figures: 33 | model: huatuo... | generated: ...` -> dict."""
    out: dict = {}
    for part in (line or "").split("|"):
        if ":" not in part:
            continue
        k, v = part.split(":", 1)
        out[k.strip().lower()] = v.strip()
    return out


# ---------------------------------------------------------------------------
# Tag -> chunk kind
# ---------------------------------------------------------------------------

TAG_KIND = {
    "con": "prose", "def": "definition", "key": "keypoint",
    "clin": "clinical", "sum": "summary", "cap": "caption",
    "desc": "figure_description", "tbl": "table", "ref": "reference",
    "obj": "objective",
}
LIST_TAGS = ("obj", "key", "def", "ref")


@dataclass
class _Segment:
    kind: str
    text: str
    section_path: list[str]
    figure_ref: Optional[str] = None
    figure_refs: list[str] = field(default_factory=list)
    table_refs: list[str] = field(default_factory=list)
    heading_level: int = 0
    section_id: str = ""
    # `<fig>`/`<tbl>` this segment's text came out of, so the chunk it becomes
    # can be bound back to that block once ids are minted.
    element_id: str = ""


# ---------------------------------------------------------------------------
# Tree -> segments
# ---------------------------------------------------------------------------

def section_level(sec: Node) -> int:
    """The `level` attribute of a `<sec>`, defaulting to 2 if absent or junk."""
    try:
        return int(sec.attrs.get("level") or 2)
    except ValueError:
        return 2


def nest_sections(sections: list[Node]) -> list[Node]:
    """Rebuild the section tree from a flat list, using the `level` attribute.

    The rewriter emits sections flat and carries depth in `level`, so a level-2
    subsection is a *sibling* of the level-1 section it belongs under. Left
    alone, every section would hang off the document root and `section_path`
    would lose the parent heading that says what the subsection is a subsection
    of. Each section is appended to the nearest preceding section of a lower
    level; anything with no such parent stays at the top.

    Mutates the nodes' `children` in place and returns the new top-level list.
    A document whose sections are already properly nested (an older rewriter, or
    one uniform level throughout) comes back unchanged.
    """
    top: list[Node] = []
    stack: list[Node] = []
    for sec in sections:
        level = section_level(sec)
        while stack and section_level(stack[-1]) >= level:
            stack.pop()
        if stack:
            stack[-1].children.append(sec)
        else:
            top.append(sec)
        stack.append(sec)
    return top


def _walk_section(sec: Node, path: list[str], segs: list[_Segment],
                  figures: list[Figure], tables: list[Table],
                  review: list[dict]) -> None:
    head = sec.find("head")
    raw_title = clean_text(head.flat_text()) if head else ""
    title = flatten_math(raw_title)
    sid = sec.attrs.get("id", "")
    level = section_level(sec)
    here = path + ([title] if title else [])
    # A section with no id of its own still has to be addressable, or its
    # content would fall back into the document-level graph and become
    # unreachable by a section subset. The heading slug is stable enough for
    # that, and `sections()` reports whatever is used either way.
    #
    # The rewriter derives its own ids the same way, but from the heading with
    # its markup still in place, so a heading carrying LaTeX or a `<sub>` yields
    # an id spelled out of the markup: `mathsf-p-mathsf-k-mathsf-a-values-...`,
    # `p-k-sub-a-sub-values-...`. Its id is kept when the two agree, allowing
    # for the different length each is truncated at, and re-derived when they
    # disagree, because the id names a graph.
    derived = slug(title)
    if not sid or not (sid.startswith(derived) or derived.startswith(sid)):
        sid = derived
    if title:
        segs.append(_Segment("heading", title, here, heading_level=level,
                             section_id=sid))

    for child in sec.children:
        tag = child.tag
        if tag == "head":
            continue
        if tag == "sec":
            _walk_section(child, here, segs, figures, tables, review)
            continue
        if tag == "note":
            if child.attrs.get("status") == "failed" or _FAILED_RE.search(child.flat_text()):
                review.append({"stage": "stage1-tagged", "section": sid or title,
                               "reason": "section not generated by the rewriter",
                               "planned": clean_text(child.flat_text())[:300]})
            continue
        if tag == "fig":
            _collect_figure(child, here, segs, figures, review, section_id=sid)
            continue
        if tag == "tbl":
            _collect_table(child, here, segs, tables, section_id=sid)
            continue

        kind = TAG_KIND.get(tag)
        if kind is None:
            continue
        if tag in LIST_TAGS:
            body = "\n".join(split_items(child))
        else:
            body = clean_text(child.flat_text())
        body = drop_formula_sentences(body)
        if not body:
            continue
        # An older rewriter build wrote the failure notice as ordinary <con>
        # prose. Extracting "This section could not be generated" as fact would
        # be worse than useless, so it is caught here too.
        if _FAILED_RE.search(body):
            review.append({"stage": "stage1-tagged", "section": sid or title,
                           "reason": "section not generated by the rewriter",
                           "planned": body[:300]})
            continue
        body, fig_anchors, tbl_anchors = lift_anchors(body)
        if body:
            segs.append(_Segment(kind, body, here, figure_refs=fig_anchors,
                                 table_refs=tbl_anchors, section_id=sid))


def _collect_figure(node: Node, path: list[str], segs: list[_Segment],
                    figures: list[Figure], review: list[dict],
                    section_id: str = "") -> None:
    fid = node.attrs.get("id", "").strip()
    marker = ""
    body = node.text or ""
    m = FIGURE_MARKER_RE.search(body)
    if m:
        marker = m.group(0)
        if not fid:
            fid = m.group(1).strip()
    if not fid:
        review.append({"stage": "stage1-figure", "reason": "figure block with no id"})
        return

    cap_node, desc_node = node.find("cap"), node.find("desc")
    caption = flatten_math(clean_text(cap_node.flat_text())) if cap_node else ""
    desc = drop_formula_sentences(
        clean_text(desc_node.flat_text()) if desc_node else "")
    # A caption may itself cite another figure ("see Figure 4-4"). The anchor is
    # dropped rather than kept: `referenced_from` means the prose that sent the
    # reader to this figure, and one caption pointing at another is not that.
    caption, _, _ = lift_anchors(caption)
    desc, desc_figs, desc_tbls = lift_anchors(desc)

    segs.append(_Segment("figure_marker", marker or f"[FIGURE:{fid}]", path,
                         figure_ref=fid, section_id=section_id))
    if caption:
        segs.append(_Segment("caption", caption, path, figure_ref=fid,
                             section_id=section_id))
    if desc:
        # A populated <desc> is not visual prose: it is what a mermaid diagram
        # or an attached data table became, restated one claim per sentence on
        # the same contract as body text, so it is chunked rather than parked on
        # the Figure. Whether Stage 2 then reads it is
        # `config.EXTRACTABLE_CHUNK_KINDS`, which currently leaves it out.
        segs.append(_Segment("figure_content", desc, path, figure_ref=fid,
                             figure_refs=desc_figs, table_refs=desc_tbls,
                             section_id=section_id, element_id=fid))

    figures.append(Figure(fig_id=fid, caption=caption, referenced_from="",
                          image_path=node.attrs.get("src", "").strip(),
                          marker=marker or f"[FIGURE:{fid}]",
                          description=desc, section_id=section_id,
                          label=node.attrs.get("label", "").strip(),
                          panel=node.attrs.get("panel", "").strip()))


def _collect_table(node: Node, path: list[str], segs: list[_Segment],
                   tables: list[Table], section_id: str = "") -> None:
    """A `<tbl>` block -> a Table record plus its segments.

    The caption and the restated grid are split rather than flattened together:
    the `<con>` is assertable text and becomes an extractable chunk, while the
    `<cap>` only names the table ("Bond Energies for Atoms of Biologic
    Significance") and would contribute a subject-less fragment to the middle of
    it. A table with no id is still worth its content, so it keeps the chunk and
    loses only its `<tblref>` addressability.
    """
    tid = node.attrs.get("id", "").strip()
    cap_node = node.find("cap")
    caption = flatten_math(clean_text(cap_node.flat_text())) if cap_node else ""
    caption, _, _ = lift_anchors(caption)
    body = "\n".join(clean_text(c.flat_text()) for c in node.findall("con"))
    body = drop_formula_sentences(body)
    body = "\n".join(ln for ln in body.splitlines() if ln.strip())

    if caption:
        segs.append(_Segment("table_caption", caption, path,
                             section_id=section_id, element_id=tid))
    if body:
        body, fig_anchors, tbl_anchors = lift_anchors(body)
        segs.append(_Segment("table", body, path, figure_refs=fig_anchors,
                             table_refs=tbl_anchors, section_id=section_id,
                             element_id=tid))
    if tid:
        tables.append(Table(table_id=tid, caption=caption,
                            label=node.attrs.get("label", "").strip(),
                            section_id=section_id))


def build_segments(root: Node, review: list[dict]
                   ) -> tuple[list[_Segment], list[Figure], list[Table],
                              Source]:
    segs: list[_Segment] = []
    figures: list[Figure] = []
    tables: list[Table] = []

    meta = root.find("meta")
    title = origin = generator = generated = topic = book = ""
    if meta:
        t = meta.find("title")
        title = flatten_math(clean_text(t.flat_text())) if t else ""
        tp = meta.find("topic")
        topic = clean_text(tp.flat_text()) if tp else ""
        sn = meta.find("src")
        if sn:
            info = parse_src(sn.flat_text())
            origin = info.get("source", "")
            generator = info.get("model", "")
            generated = info.get("generated", "")
            book = info.get("book", "")

    if title:
        segs.append(_Segment("heading", title, [], heading_level=1))

    obj = root.find("obj")
    if obj:
        items = flatten_math("\n".join(split_items(obj)))
        if items:
            segs.append(_Segment("objective", items, [title] if title else []))

    for sec in nest_sections(root.findall("sec")):
        _walk_section(sec, [title] if title else [], segs, figures, tables,
                      review)

    # `<def>` moved from inside a section to the foot of the document, where the
    # rewriter now puts the chapter glossary. Walking only the sections would
    # drop it silently, and a glossary is the densest definition text in the
    # document.
    for tag in ("sum", "def", "ref"):
        node = root.find(tag)
        if not node:
            continue
        body = ("\n".join(split_items(node)) if tag in LIST_TAGS
                else clean_text(node.flat_text()))
        # `<ref>` is a passage and never reaches the extractor, so a citation
        # that happens to carry math keeps its sentence and only loses the
        # markup.
        body = (flatten_math(body) if tag == "ref"
                else drop_formula_sentences(body))
        if body:
            segs.append(_Segment(TAG_KIND[tag], body, [title] if title else []))

    stem = os.path.splitext(os.path.basename(origin))[0] if origin else ""
    source = Source(source_id=stem or "document", title=title or stem or "Document",
                    section=topic, origin=origin, generator=generator,
                    generated_at=generated, edition=book)
    return segs, figures, tables, source


# ---------------------------------------------------------------------------
# Segments -> normalized file + chunks
# ---------------------------------------------------------------------------

class _Writer:
    def __init__(self):
        self.buf: list[str] = []
        self.pos = 0

    def write(self, text: str) -> tuple[int, int]:
        start = self.pos
        self.buf.append(text)
        self.pos += len(text)
        end = self.pos
        self.buf.append("\n\n")
        self.pos += 2
        return start, end

    def value(self) -> str:
        return "".join(self.buf)


def _merge(segs: list[_Segment], max_chars: int) -> list[list[_Segment]]:
    """Group consecutive same-kind CHUNK segments in one section, so a relation
    spanning two paragraphs stays inside one Stage-2 call. Passages and figure
    text are never merged: they stay one-to-one with their source element."""
    groups: list[list[_Segment]] = []
    for s in segs:
        prev = groups[-1][0] if groups else None
        if (prev and s.kind == prev.kind and s.kind in config.CHUNK_KINDS
                and prev.section_path == s.section_path
                and prev.section_id == s.section_id
                # Two tables in one section restate two different grids; merging
                # them would produce a chunk that no single <tblref> points at.
                and prev.element_id == s.element_id
                and sum(len(x.text) + 2 for x in groups[-1]) + len(s.text) <= max_chars):
            groups[-1].append(s)
        else:
            groups.append([s])
    return groups


def assemble(segs: list[_Segment], review: Optional[list] = None,
             max_chars: int = None):
    """Segments -> (text, chunks, passages, figure spans, table spans, blocks).

    Everything is written to the normalized file and every piece gets a span,
    but only assertable text becomes a `Chunk`. Guarantees
    `normalized[start:end] == text` for chunks, passages and figure spans alike.

    `fig_spans` maps a figure id to its caption/description spans and
    `tbl_spans` a table id to its caption span. `blocks` is
    `{element_id: chunk_id}` for the `<fig>`/`<tbl>` blocks whose own content
    became a chunk, which binds a table to the sentences its grid became.
    """
    limit = config.MAX_CHUNK_CHARS if max_chars is None else max_chars
    rev = review if review is not None else []
    w = _Writer()
    chunks: list[Chunk] = []
    passages: list[Passage] = []
    fig_spans: dict[str, dict[str, list[int]]] = {}
    tbl_spans: dict[str, list[int]] = {}
    blocks: dict[str, str] = {}
    counter = itertools.count(1)
    pcounter = itertools.count(1)
    seen: dict[str, str] = {}

    for group in _merge(segs, limit):
        head = group[0]
        text = "\n\n".join(s.text for s in group)
        if head.kind == "heading":
            w.write("#" * max(1, head.heading_level) + " " + text)
            continue
        start, end = w.write(text)
        if head.kind == "figure_marker":
            continue
        if head.kind in ("caption", "figure_description"):
            slot = "caption" if head.kind == "caption" else "description"
            fig_spans.setdefault(head.figure_ref or "", {})[slot] = [start, end]
            continue
        if head.kind == "table_caption":
            # A caption names its table without asserting anything about it, so
            # it is written and positioned but never extracted, the same way a
            # figure caption is.
            tbl_spans[head.element_id] = [start, end]
            continue
        if head.kind in config.PASSAGE_KINDS:
            passages.append(Passage(
                passage_id=f"p{next(pcounter):03d}", kind=head.kind, text=text,
                char_start=start, char_end=end,
                section_path=list(head.section_path),
                section_id=head.section_id))
            continue
        kind = head.kind
        # The rewriter's <key> often restates <con> verbatim, and in the sample
        # one section's two blocks are byte-identical. Extracting both pays a
        # Stage-2 call twice for one fact, so exact repeats are demoted rather
        # than dropped: the text stays in the file, it just isn't re-extracted.
        key = " ".join(text.split()).lower()
        if key in seen:
            rev.append({"stage": "stage1-duplicate", "duplicate_of": seen[key],
                        "kind": kind, "text": text[:120]})
            kind = "duplicate"
        cid = f"c{next(counter):03d}"
        seen.setdefault(key, cid)
        if head.element_id:
            blocks.setdefault(head.element_id, cid)
        chunks.append(Chunk(
            chunk_id=cid, text=text, char_start=start, char_end=end,
            section_path=list(head.section_path), kind=kind,
            figure_refs=sorted({r for s in group for r in s.figure_refs}),
            table_refs=sorted({r for s in group for r in s.table_refs}),
            section_id=head.section_id,
        ))
    return w.value(), chunks, passages, fig_spans, tbl_spans, blocks


def _bind_figures(figures: list[Figure], chunks: list[Chunk], fig_spans: dict,
                  blocks: dict, figures_dir: str, figures_ext: str,
                  verify_images: bool, review: list[dict]) -> None:
    """Attach spans, the citing chunk, the content chunk and the image path.

    `blocks` maps a `<fig>`/`<tbl>` id to the chunk its own content became,
    which is how a populated `<desc>` gets back to the figure it describes.
    Mutates the `Figure` objects and appends to `review`; returns nothing.
    """
    by_id = {f.fig_id: f for f in figures}
    for fid, spans in fig_spans.items():
        fig = by_id.get(fid)
        if fig is not None:
            fig.caption_span = spans.get("caption")
            fig.description_span = spans.get("description")
    for fid, cid in blocks.items():
        fig = by_id.get(fid)
        if fig is not None:
            fig.content_chunk = cid
    for c in chunks:
        # `referenced_from` is the prose that ACTUALLY points at the figure, via
        # a [[FIG:id]] anchor -- never the figure's own caption, which would make
        # every figure look referenced and hide the ones that aren't.
        for ref in c.figure_refs:
            target = by_id.get(ref)
            if target is not None and not target.referenced_from:
                target.referenced_from = c.chunk_id
    for fig in figures:
        if not fig.referenced_from:
            # The rewriter placed this figure in a section and then never wove an
            # anchor for it into the prose. Stage 5 can still bridge its caption,
            # but nothing in the text explains why the reader is looking at it.
            review.append({"stage": "stage1-figure", "fig_id": fig.fig_id,
                           "reason": "figure never anchored in prose"})
    for fig in figures:
        # The image path comes from the `<fig src="...">` the rewriter carried
        # over from the original document. It is a content-hash filename, so it
        # cannot be derived from `fig_id`; `figures_ext` only ever applies to a
        # src that arrived without a suffix, and `figures_dir` relocates a
        # relative src to wherever the image tree actually sits.
        path = fig.image_path
        if not path:
            review.append({"stage": "stage1-figure", "fig_id": fig.fig_id,
                           "reason": "figure has no src image"})
            continue
        if figures_ext and not os.path.splitext(path)[1]:
            path += figures_ext if figures_ext.startswith(".") else "." + figures_ext
        if figures_dir and not os.path.isabs(path):
            path = os.path.join(figures_dir, path)
        fig.image_path = path
        if verify_images and not os.path.exists(fig.image_path):
            review.append({"stage": "stage1-figure", "fig_id": fig.fig_id,
                           "reason": "image file not found", "path": fig.image_path})


def _bind_tables(tables: list[Table], chunks: list[Chunk], tbl_spans: dict,
                 blocks: dict, review: list[dict]) -> None:
    """Attach each table's caption span, content chunk and citing chunk.

    `tbl_spans` is `{table_id: [start, end]}` for captions and `blocks` is
    `{element_id: chunk_id}` from `assemble`. A table whose grid produced no
    chunk, or that no prose cites, is flagged for review rather than dropped.
    Mutates the `Table` objects; returns nothing.
    """
    by_id = {t.table_id: t for t in tables}
    for tid, span in tbl_spans.items():
        table = by_id.get(tid)
        if table is not None:
            table.caption_span = span
    for tid, cid in blocks.items():
        table = by_id.get(tid)
        if table is not None:
            table.content_chunk = cid
    for c in chunks:
        for ref in c.table_refs:
            target = by_id.get(ref)
            if target is not None and not target.referenced_from:
                target.referenced_from = c.chunk_id
    for table in tables:
        if not table.content_chunk:
            review.append({"stage": "stage1-table", "table_id": table.table_id,
                           "reason": "table has no restated content"})
        if not table.referenced_from:
            review.append({"stage": "stage1-table", "table_id": table.table_id,
                           "reason": "table never cited in prose"})


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_file(md_path: str, *, normalized_path: str = None, doc_id: str = None,
               source: Source = None, figures_dir: str = "", figures_ext: str = "",
               verify_images: bool = False) -> Document:
    """Tagged rewritten markdown -> normalized text file + Stage-1 Document."""
    started_at = time.time()
    console.announce_stage(1, "parse",
                           "tagged markdown -> normalized text + IR")
    console.announce_step(f"reading {md_path}")
    with open(md_path, encoding="utf-8") as fh:
        raw = fh.read()
    console.announce_detail(console.format_count(len(raw), "character"))

    stem = os.path.splitext(os.path.basename(md_path))[0]
    # Written into the artifacts directory rather than beside the source: the
    # input may live in a read-only or shared location, and chunk offsets index
    # into this file, so it belongs with the graph it describes.
    normalized_path = normalized_path or config.artifact_path(
        stem + ".normalized.md")

    # Inline markup is unwrapped before anything else looks at the text, not
    # during the block parse: `parse_tagged` would lift a `<figref>` out of the
    # sentence it sits in, and `scan_markers` would read the wrapper as content.
    raw = normalize_inline(raw)

    console.announce_step("scanning for rewriter markers and failed sections")
    review: list[dict] = scan_markers(raw)
    console.announce_detail(console.format_count(len(review), "marker")
                            + " flagged for review")

    console.announce_step("parsing tags into sections, figures and segments")
    root = parse_tagged(raw)
    segs, figures, tables, parsed_source = build_segments(root, review)
    console.announce_detail(f"{console.format_count(len(segs), 'segment')}, "
                            f"{console.format_count(len(figures), 'figure')}, "
                            f"{console.format_count(len(tables), 'table')}")

    console.announce_step(
        f"assembling chunks (same-kind runs merge up to "
        f"{config.MAX_CHUNK_CHARS:,} characters)")
    normalized, chunks, passages, fig_spans, tbl_spans, blocks = assemble(
        segs, review)
    kind_counts: dict[str, int] = {}
    for chunk in chunks:
        kind_counts[chunk.kind] = kind_counts.get(chunk.kind, 0) + 1
    console.announce_detail(
        f"{console.format_count(len(chunks), 'chunk')} for Stage 2: "
        + ", ".join(f"{kind} {count}"
                    for kind, count in sorted(kind_counts.items())))
    passage_counts: dict[str, int] = {}
    for passage in passages:
        passage_counts[passage.kind] = passage_counts.get(passage.kind, 0) + 1
    console.announce_detail(
        f"{console.format_count(len(passages), 'passage')} kept but never "
        f"asserted: "
        + ", ".join(f"{kind} {count}"
                    for kind, count in sorted(passage_counts.items())))

    console.announce_step("binding figures and tables to their chunks")
    _bind_figures(figures, chunks, fig_spans, blocks, figures_dir, figures_ext,
                  verify_images, review)
    _bind_tables(tables, chunks, tbl_spans, blocks, review)
    console.announce_detail(
        f"{sum(1 for f in figures if f.referenced_from)}/{len(figures)} "
        f"figures and {sum(1 for t in tables if t.referenced_from)}/"
        f"{len(tables)} tables cited from prose")

    console.announce_step(f"writing normalized text -> {normalized_path}")
    with open(normalized_path, "w", encoding="utf-8") as fh:
        fh.write(normalized)

    src = source or parsed_source
    if not src.source_id or src.source_id == "document":
        src.source_id = stem
    doc = Document(
        doc_id=doc_id or src.source_id, source=src, chunks=chunks, figures=figures,
        tables=tables, passages=passages, needs_review=review,
        source_path=os.path.abspath(md_path),
        normalized_path=os.path.abspath(normalized_path),
    )
    console.announce_step("verifying every offset against the normalized text")
    for item in list(doc.chunks) + list(doc.passages):
        assert normalized[item.char_start:item.char_end] == item.text, "offset drift"
    for fig in doc.figures:
        for span, text in ((fig.caption_span, fig.caption),
                           (fig.description_span, fig.description)):
            if span:
                assert normalized[span[0]:span[1]] == text, \
                    f"offset drift in figure {fig.fig_id}"
    for table in doc.tables:
        if table.caption_span:
            assert normalized[table.caption_span[0]:table.caption_span[1]] \
                == table.caption, f"offset drift in table {table.table_id}"
    console.announce_finished(
        "stage 1", started_at,
        f"{src.source_id}, "
        f"{console.format_count(len(doc.sections()), 'section')}, "
        f"{console.format_count(len(chunks), 'chunk')}")
    return doc


def run(md_path: str, **kw) -> Document:
    return parse_file(md_path, **kw)
