"""Stage 1 — tagged rewritten markdown -> structured IR.

The input is no longer the raw PDF-converted markdown. `rewrite_medical_md.py`
now owns that job: it rewrites the slide dump into a fresh, tagged study
document, and *that* is what this stage parses. Everything Stage 1 used to do
by inference — telling figure prose from material content, flattening bullets,
distributing headings, guarding a rewrite — is done structurally upstream by
the tags. So this stage does no rewriting, makes no LLM calls, and reaches no
judgement about what any passage means. It maps tags onto chunk kinds:

    <con>   -> prose               <cap>  -> caption
    <def>   -> definition          <desc> -> figure_description
    <key>   -> keypoint            <tbl>  -> table
    <clin>  -> clinical            <ref>  -> reference
    <sum>   -> summary             <obj>  -> objective

Only assertable text becomes a `Chunk`. Captions and descriptions are stored on
the `Figure` — chunking them as well was pure duplication that no stage read.
Objectives, tables and bibliography become `Passage`s: retained, with offsets,
but never assertable. All of it is still written to the normalized file, so
every piece of the document has a position even when it is not a chunk.

Two things this stage still owns, because nothing else can:

  * **Offsets.** It writes a tag-free rendering to `Document.normalized_path`
    and every chunk indexes into that file exactly, so Stage 2's substring
    grounding guards keep working and any triple can be traced back to text.
  * **Provenance.** The document it parses was written by a model. `<src>`
    records what the rewriter was given and which model wrote it, and those go
    into `Source.origin` / `.generator` so Stage 6 can assert the original as
    `dcterms:source` and the rewrite as `prov:wasGeneratedBy`. Without that the
    graph would report model-authored prose as what the textbook said.

The parser is deliberately tolerant: the tagged format has drifted across
rewriter versions (list items appear either as `<pt>`/`<term>`/`<goal>`
elements or as bare `- ` bullets; headings sometimes keep their `#` markers;
failed sections appear either as `<note status="failed">` or as a parenthetical
inside `<con>`), and a corpus generated by an older build must still parse.

Stdlib only. No network, no models, nothing to configure.
"""
from __future__ import annotations

import itertools
import os
import re
from dataclasses import dataclass, field
from typing import Optional

from .ir import Document, Source, Chunk, Figure, Passage
from . import config

# ---------------------------------------------------------------------------
# Tolerant tag scanner
# ---------------------------------------------------------------------------

KNOWN_TAGS = ("doc", "meta", "title", "topic", "src", "obj", "goal", "sec",
              "head", "con", "fig", "cap", "desc", "key", "pt", "def", "term",
              "clin", "tbl", "note", "sum", "ref", "cit")

_TAG_RE = re.compile(r"<(/?)(" + "|".join(KNOWN_TAGS) + r")(\s[^>]*)?>", re.I)
_ATTR_RE = re.compile(r'(\w+)\s*=\s*"([^"]*)"')

# `[FIGURE:p2_b3]` — the marker carried through from the original document.
FIGURE_MARKER_RE = re.compile(r"\[\s*FIGURE\s*:\s*([^\]\n]+?)\s*\]", re.I)
# `[[FIG:p2_b3]]` — the rewriter's inline anchor, pointing at a figure block.
FIG_ANCHOR_RE = re.compile(r"\[\[\s*FIG\s*:\s*([^\]\n]+?)\s*\]\]")

_MD_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+", re.M)
_BULLET_RE = re.compile(r"^\s*(?:[-+\u2022\u2023\u25aa\u25e6]|\*(?!\*)|\d+[.)])\s+")
_EMPHASIS_RE = re.compile(r"(\*{1,3}|_{2,3})(?=\S)(.+?)(?<=\S)\1", re.S)

_FAILED_RE = re.compile(r"could not be generated", re.I)


@dataclass
class Node:
    tag: str
    attrs: dict = field(default_factory=dict)
    children: list = field(default_factory=list)
    text: str = ""

    def find(self, tag: str) -> Optional["Node"]:
        for c in self.children:
            if c.tag == tag:
                return c
        return None

    def findall(self, tag: str) -> list:
        return [c for c in self.children if c.tag == tag]

    def flat_text(self) -> str:
        parts = [self.text]
        for c in self.children:
            parts.append(c.flat_text())
        return "\n".join(p for p in parts if p.strip()).strip()


def parse_tagged(text: str) -> Node:
    """Tagged document -> a shallow node tree.

    Hand-rolled rather than XML: the body carries markdown, bare ampersands and
    `[[FIG:...]]` anchors, so a strict parser would reject documents that are
    perfectly usable. Unknown tags fall through as text; an unclosed tag is
    closed implicitly when its parent closes.
    """
    root = Node("doc")
    stack = [root]
    pos = 0
    for m in _TAG_RE.finditer(text):
        chunk = text[pos:m.start()]
        if chunk.strip():
            stack[-1].text = (stack[-1].text + "\n" + chunk).strip()
        pos = m.end()
        closing, tag = bool(m.group(1)), m.group(2).lower()
        if closing:
            for i in range(len(stack) - 1, 0, -1):
                if stack[i].tag == tag:
                    del stack[i:]
                    break
        else:
            attrs = dict(_ATTR_RE.findall(m.group(3) or ""))
            node = Node(tag, attrs)
            if tag == "doc" and len(stack) == 1:
                root.attrs.update(attrs)
                continue
            stack[-1].children.append(node)
            stack.append(node)
    tail = text[pos:]
    if tail.strip():
        stack[-1].text = (stack[-1].text + "\n" + tail).strip()
    return root


# ---------------------------------------------------------------------------
# Text cleanup (repair only — never rewriting)
# ---------------------------------------------------------------------------

def strip_emphasis(text: str) -> str:
    prev = None
    while prev != text:
        prev = text
        text = _EMPHASIS_RE.sub(lambda m: m.group(2), text)
    return text


MARKER_SCANS = (
    ("heading marker", re.compile(r"^\s{0,3}#{1,6}\s+", re.M)),
    ("bold/italic marker", re.compile(r"\*")),
    ("bullet marker", re.compile(r"^\s*(?:[-+\u2022]|\d+[.)])\s+", re.M)),
)


def scan_markers(raw: str) -> list[dict]:
    """Report markdown markers left in the tagged document.

    The current rewriter emits none of these — the tags carry the structure, so
    a `##` or a `**` means it regressed. `clean_text` still repairs them, but
    repairing silently would hide the regression, so each kind is reported once
    with an example. Applies to tag *content* only; `[FIGURE:id]` markers and
    `[[FIG:id]]` anchors are not markdown and are left alone.
    """
    body = _TAG_RE.sub("", raw)
    body = FIGURE_MARKER_RE.sub("", FIG_ANCHOR_RE.sub("", body))
    out = []
    for label, pattern in MARKER_SCANS:
        hits = pattern.findall(body)
        if hits:
            line = next((ln.strip() for ln in body.splitlines() if pattern.search(ln)), "")
            out.append({"stage": "stage1-marker", "reason": f"{label} in tagged content",
                        "count": len(hits), "example": line[:120]})
    return out


def clean_text(text: str) -> str:
    """Remove markdown scaffolding, if any survived.

    Repair, not rewriting — the words are untouched. The current rewriter leaves
    none of this behind; `scan_markers` reports whatever turns up so a silent
    repair cannot mask a rewriter regression.
    """
    out = []
    for line in text.splitlines():
        line = _MD_HEADING_RE.sub("", line)
        line = _BULLET_RE.sub("", line, count=1)
        line = strip_emphasis(line)
        # Whatever asterisks survive emphasis-matching are orphans from the
        # older rewriter's bullet bug ("- *Follicular cells** — ..."), which
        # leaves one behind mid-line. They are markup, never content, and left
        # in they would sit inside Stage 2's span offsets and evidence strings.
        line = line.replace("*", "")
        line = re.sub(r"[ \t]{2,}", " ", line).strip()
        if line:
            out.append(line)
    return "\n".join(out).strip()


def split_items(node: Node) -> list[str]:
    """Items of a list container, whichever way the rewriter emitted them:
    as child elements (`<pt>`, `<term>`, `<goal>`, `<cit>`) or as `- ` bullets."""
    items = [clean_text(c.flat_text()) for c in node.children
             if c.tag in ("pt", "term", "goal", "cit")]
    items = [i for i in items if i]
    if items:
        return items
    return [ln for ln in (clean_text(node.text)).splitlines() if ln.strip()]


def lift_anchors(text: str) -> tuple[str, list[str]]:
    """Pull `[[FIG:id]]` anchors out of prose, returning (text, fig_ids).

    They must not survive into chunk text: Stage 2 requires its `evidence` to be
    an exact substring of the chunk, and an anchor sitting mid-sentence corrupts
    every span offset after it. The association is kept on the chunk instead.
    """
    ids = [m.group(1).strip() for m in FIG_ANCHOR_RE.finditer(text)]
    cleaned = re.sub(r"[ \t]*" + FIG_ANCHOR_RE.pattern + r"[ \t]*", " ", text)
    cleaned = re.sub(r"[ \t]{2,}", " ", cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip(), ids


def parse_src(line: str) -> dict:
    """`source: x.md | figures: 33 | model: huatuo... | generated: ...` -> dict."""
    out: dict = {}
    for part in (line or "").split("|"):
        if ":" not in part:
            continue
        k, v = part.split(":", 1)
        out[k.strip().lower()] = v.strip()
    return out


# ---------------------------------------------------------------------------
# Tag -> chunk kind
# ---------------------------------------------------------------------------

TAG_KIND = {
    "con": "prose", "def": "definition", "key": "keypoint",
    "clin": "clinical", "sum": "summary", "cap": "caption",
    "desc": "figure_description", "tbl": "table", "ref": "reference",
    "obj": "objective",
}
LIST_TAGS = ("obj", "key", "def", "ref")


@dataclass
class _Segment:
    kind: str
    text: str
    section_path: list[str]
    figure_ref: Optional[str] = None
    figure_refs: list[str] = field(default_factory=list)
    heading_level: int = 0


# ---------------------------------------------------------------------------
# Tree -> segments
# ---------------------------------------------------------------------------

def _walk_section(sec: Node, path: list[str], segs: list[_Segment],
                  figures: list[Figure], review: list[dict]) -> None:
    head = sec.find("head")
    title = clean_text(head.flat_text()) if head else ""
    sid = sec.attrs.get("id", "")
    try:
        level = int(sec.attrs.get("level") or 2)
    except ValueError:
        level = 2
    here = path + ([title] if title else [])
    if title:
        segs.append(_Segment("heading", title, here, heading_level=level))

    for child in sec.children:
        tag = child.tag
        if tag == "head":
            continue
        if tag == "sec":
            _walk_section(child, here, segs, figures, review)
            continue
        if tag == "note":
            if child.attrs.get("status") == "failed" or _FAILED_RE.search(child.flat_text()):
                review.append({"stage": "stage1-tagged", "section": sid or title,
                               "reason": "section not generated by the rewriter",
                               "planned": clean_text(child.flat_text())[:300]})
            continue
        if tag == "fig":
            _collect_figure(child, here, segs, figures, review)
            continue

        kind = TAG_KIND.get(tag)
        if kind is None:
            continue
        if tag in LIST_TAGS:
            body = "\n".join(split_items(child))
        else:
            body = clean_text(child.flat_text())
        if not body:
            continue
        # An older rewriter build wrote the failure notice as ordinary <con>
        # prose. Extracting "This section could not be generated" as fact would
        # be worse than useless, so it is caught here too.
        if _FAILED_RE.search(body):
            review.append({"stage": "stage1-tagged", "section": sid or title,
                           "reason": "section not generated by the rewriter",
                           "planned": body[:300]})
            continue
        body, anchors = lift_anchors(body)
        if body:
            segs.append(_Segment(kind, body, here, figure_refs=anchors))


def _collect_figure(node: Node, path: list[str], segs: list[_Segment],
                    figures: list[Figure], review: list[dict]) -> None:
    fid = node.attrs.get("id", "").strip()
    marker = ""
    body = node.text or ""
    m = FIGURE_MARKER_RE.search(body)
    if m:
        marker = m.group(0)
        if not fid:
            fid = m.group(1).strip()
    if not fid:
        review.append({"stage": "stage1-figure", "reason": "figure block with no id"})
        return

    cap_node, desc_node = node.find("cap"), node.find("desc")
    caption = clean_text(cap_node.flat_text()) if cap_node else ""
    desc = clean_text(desc_node.flat_text()) if desc_node else ""

    segs.append(_Segment("figure_marker", marker or f"[FIGURE:{fid}]", path,
                         figure_ref=fid))
    if caption:
        segs.append(_Segment("caption", caption, path, figure_ref=fid))
    if desc:
        segs.append(_Segment("figure_description", desc, path, figure_ref=fid))

    figures.append(Figure(fig_id=fid, image_path="", caption=caption,
                          referenced_from="", marker=marker or f"[FIGURE:{fid}]",
                          description=desc))


def build_segments(root: Node, review: list[dict]) -> tuple[list[_Segment], list[Figure], Source]:
    segs: list[_Segment] = []
    figures: list[Figure] = []

    meta = root.find("meta")
    title = origin = generator = generated = topic = ""
    if meta:
        t = meta.find("title")
        title = clean_text(t.flat_text()) if t else ""
        tp = meta.find("topic")
        topic = clean_text(tp.flat_text()) if tp else ""
        sn = meta.find("src")
        if sn:
            info = parse_src(sn.flat_text())
            origin = info.get("source", "")
            generator = info.get("model", "")
            generated = info.get("generated", "")

    if title:
        segs.append(_Segment("heading", title, [], heading_level=1))

    obj = root.find("obj")
    if obj:
        items = "\n".join(split_items(obj))
        if items:
            segs.append(_Segment("objective", items, [title] if title else []))

    for sec in root.findall("sec"):
        _walk_section(sec, [title] if title else [], segs, figures, review)

    for tag in ("sum", "ref"):
        node = root.find(tag)
        if not node:
            continue
        body = "\n".join(split_items(node)) if tag in LIST_TAGS else clean_text(node.flat_text())
        if body:
            segs.append(_Segment(TAG_KIND[tag], body, [title] if title else []))

    stem = os.path.splitext(os.path.basename(origin))[0] if origin else ""
    source = Source(source_id=stem or "document", title=title or stem or "Document",
                    section=topic, origin=origin, generator=generator,
                    generated_at=generated)
    return segs, figures, source


# ---------------------------------------------------------------------------
# Segments -> normalized file + chunks
# ---------------------------------------------------------------------------

class _Writer:
    def __init__(self):
        self.buf: list[str] = []
        self.pos = 0

    def write(self, text: str) -> tuple[int, int]:
        start = self.pos
        self.buf.append(text)
        self.pos += len(text)
        end = self.pos
        self.buf.append("\n\n")
        self.pos += 2
        return start, end

    def value(self) -> str:
        return "".join(self.buf)


def _merge(segs: list[_Segment], max_chars: int) -> list[list[_Segment]]:
    """Group consecutive same-kind CHUNK segments in one section, so a relation
    spanning two paragraphs stays inside one Stage-2 call. Passages and figure
    text are never merged: they stay one-to-one with their source element."""
    groups: list[list[_Segment]] = []
    for s in segs:
        prev = groups[-1][0] if groups else None
        if (prev and s.kind == prev.kind and s.kind in config.CHUNK_KINDS
                and prev.section_path == s.section_path
                and sum(len(x.text) + 2 for x in groups[-1]) + len(s.text) <= max_chars):
            groups[-1].append(s)
        else:
            groups.append([s])
    return groups


def assemble(segs: list[_Segment], review: Optional[list] = None,
             max_chars: int = None):
    """Segments -> (normalized text, chunks, passages, figure spans).

    Everything is written to the normalized file and every piece gets a span,
    but only assertable text becomes a `Chunk`. Guarantees
    `normalized[start:end] == text` for chunks, passages and figure spans alike.
    """
    limit = config.MAX_CHUNK_CHARS if max_chars is None else max_chars
    rev = review if review is not None else []
    w = _Writer()
    chunks: list[Chunk] = []
    passages: list[Passage] = []
    fig_spans: dict[str, dict[str, list[int]]] = {}
    counter = itertools.count(1)
    pcounter = itertools.count(1)
    seen: dict[str, str] = {}

    for group in _merge(segs, limit):
        head = group[0]
        text = "\n\n".join(s.text for s in group)
        if head.kind == "heading":
            w.write("#" * max(1, head.heading_level) + " " + text)
            continue
        start, end = w.write(text)
        if head.kind == "figure_marker":
            continue
        if head.kind in ("caption", "figure_description"):
            slot = "caption" if head.kind == "caption" else "description"
            fig_spans.setdefault(head.figure_ref or "", {})[slot] = [start, end]
            continue
        if head.kind in config.PASSAGE_KINDS:
            passages.append(Passage(
                passage_id=f"p{next(pcounter):03d}", kind=head.kind, text=text,
                char_start=start, char_end=end,
                section_path=list(head.section_path)))
            continue
        kind = head.kind
        # The rewriter's <key> often restates <con> verbatim, and in the sample
        # one section's two blocks are byte-identical. Extracting both pays a
        # Stage-2 call twice for one fact, so exact repeats are demoted rather
        # than dropped: the text stays in the file, it just isn't re-extracted.
        key = " ".join(text.split()).lower()
        if key in seen:
            rev.append({"stage": "stage1-duplicate", "duplicate_of": seen[key],
                        "kind": kind, "text": text[:120]})
            kind = "duplicate"
        cid = f"c{next(counter):03d}"
        seen.setdefault(key, cid)
        chunks.append(Chunk(
            chunk_id=cid, text=text, char_start=start, char_end=end,
            section_path=list(head.section_path), kind=kind,
            figure_refs=sorted({r for s in group for r in s.figure_refs}),
        ))
    return w.value(), chunks, passages, fig_spans


def _bind_figures(figures: list[Figure], chunks: list[Chunk], fig_spans: dict,
                  figures_dir: str, figures_ext: str, verify_images: bool,
                  review: list[dict]) -> None:
    by_id = {f.fig_id: f for f in figures}
    for fid, spans in fig_spans.items():
        fig = by_id.get(fid)
        if fig is not None:
            fig.caption_span = spans.get("caption")
            fig.description_span = spans.get("description")
    for c in chunks:
        # `referenced_from` is the prose that ACTUALLY points at the figure, via
        # a [[FIG:id]] anchor -- never the figure's own caption, which would make
        # every figure look referenced and hide the ones that aren't.
        for ref in c.figure_refs:
            target = by_id.get(ref)
            if target is not None and not target.referenced_from:
                target.referenced_from = c.chunk_id
    for fig in figures:
        if not fig.referenced_from:
            # The rewriter placed this figure in a section and then never wove an
            # anchor for it into the prose. Stage 5 can still bridge its caption,
            # but nothing in the text explains why the reader is looking at it.
            review.append({"stage": "stage1-figure", "fig_id": fig.fig_id,
                           "reason": "figure never anchored in prose"})
    for fig in figures:
        path = fig.fig_id
        if figures_ext and not os.path.splitext(path)[1]:
            path += figures_ext if figures_ext.startswith(".") else "." + figures_ext
        if figures_dir and not os.path.isabs(path):
            path = os.path.join(figures_dir, path)
        fig.image_path = path if (figures_dir or figures_ext) else ""
        if verify_images and fig.image_path and not os.path.exists(fig.image_path):
            review.append({"stage": "stage1-figure", "fig_id": fig.fig_id,
                           "reason": "image file not found", "path": fig.image_path})


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_file(md_path: str, *, normalized_path: str = None, doc_id: str = None,
               source: Source = None, figures_dir: str = "", figures_ext: str = "",
               verify_images: bool = False) -> Document:
    """Tagged rewritten markdown -> normalized text file + Stage-1 Document."""
    with open(md_path, encoding="utf-8") as fh:
        raw = fh.read()

    stem = os.path.splitext(os.path.basename(md_path))[0]
    # Written into the artifacts directory rather than beside the source: the
    # input may live in a read-only or shared location, and chunk offsets index
    # into this file, so it belongs with the graph it describes.
    normalized_path = normalized_path or config.artifact_path(
        stem + ".normalized.md")

    review: list[dict] = scan_markers(raw)
    root = parse_tagged(raw)
    segs, figures, parsed_source = build_segments(root, review)
    normalized, chunks, passages, fig_spans = assemble(segs, review)
    _bind_figures(figures, chunks, fig_spans, figures_dir, figures_ext,
                  verify_images, review)

    with open(normalized_path, "w", encoding="utf-8") as fh:
        fh.write(normalized)

    src = source or parsed_source
    if not src.source_id or src.source_id == "document":
        src.source_id = stem
    doc = Document(
        doc_id=doc_id or src.source_id, source=src, chunks=chunks, figures=figures,
        passages=passages, needs_review=review,
        source_path=os.path.abspath(md_path),
        normalized_path=os.path.abspath(normalized_path),
    )
    for item in list(doc.chunks) + list(doc.passages):
        assert normalized[item.char_start:item.char_end] == item.text, "offset drift"
    for fig in doc.figures:
        for span, text in ((fig.caption_span, fig.caption),
                           (fig.description_span, fig.description)):
            if span:
                assert normalized[span[0]:span[1]] == text, \
                    f"offset drift in figure {fig.fig_id}"
    return doc


def run(md_path: str, **kw) -> Document:
    return parse_file(md_path, **kw)
